# deploy always
apiVersion: v1
kind: ConfigMap
metadata:
  name: spacectl-conf
  namespace: {{ .Release.Namespace }}
data:
  environment.yml: |
    environment: helm-root
  helm-root.yml: |
    endpoints:
      config: grpc://{{ .Values.backend.services.config.endpoint }}
      identity: grpc://{{ .Values.backend.services.identity.endpoint }}
      inventory: grpc://{{ .Values.backend.services.inventory.endpoint }}
      monitoring: grpc://{{ .Values.backend.services.monitoring.endpoint }}
      plugin: grpc://{{ .Values.backend.services.plugin.endpoint }}
      repository: grpc://{{ .Values.backend.services.repository.endpoint }}
      secret: grpc://{{ .Values.backend.services.secret.endpoint }}
      statistics: grpc://{{ .Values.backend.services.statistics.endpoint }}