{{- if .Values.frontend.enabled }}
  {{- if .Values.frontend.console.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-spa-conf
  namespace: {{ .Release.Namespace }}
data:
  production.json: |
    {
      "CONSOLE_API": {
        "ENDPOINT": "{{ .Values.frontend.consoleApi.protocol }}://{{ .Values.frontend.consoleApi.endpoint }}"
      },
      "VUE_APP_API": {
        "ENDPOINT": "{{ .Values.frontend.consoleApi.protocol }}://{{ .Values.frontend.consoleApi.endpoint }}"
      },
      "GTAG_ID": "DISABLED",
      "DOMAIN_NAME_REF": "{{ .Values.frontend.console.domainName.ref }}",
      "DOMAIN_NAME": "{{ .Values.frontend.console.domainName.name }}",
      "NO_SERVER_MODE": false
    }
  {{- end }}
{{- end }}