name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  LOCATION_CHART_YAML: . # optional. for pypi upload

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Helm3
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Lint
      id: lint
      run: |
        helm lint .
